sequenceDiagram
    participant Client
    participant Codec
    participant Scheme
    participant Converter
    participant Serializer
    
    Client->>Codec: Encode(object)
    Codec->>Scheme: ObjectKinds(object)
    Scheme-->>Codec: []GVK
    Codec->>Converter: ConvertToVersion(object, targetGV)
    Converter->>Scheme: Get conversion functions
    Scheme-->>Converter: Conversion funcs
    Converter->>Converter: Execute conversion
    Converter-->>Codec: Converted object
    Codec->>Serializer: Encode(object, writer)
    Serializer-->>Codec: Bytes written
    Codec-->>Client: Success
