graph LR
    Added[ADDED<br/>New resource created]
    Modified[MODIFIED<br/>Resource updated]
    Deleted[DELETED<br/>Resource removed]
    Bookmark[BOOKMARK<br/>Sync point marker]
    Error[ERROR<br/>Watch error occurred]
    
    style Added fill:#e1f5ff
    style Modified fill:#fff4e1
    style Deleted fill:#ffe1e1
    style Bookmark fill:#f0ffe1
    style Error fill:#ffe1e1
